apiVersion: v1
kind: Service
metadata:
  name: go-app3-service
spec:
  type: ClusterIP
#  clusterIP: None
  selector:
    app: go-app3
  ports:
  - name: http-go-app3
    protocol: TCP
    port: 80
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: go-app3-preview-service
spec:
  type: ClusterIP
#  clusterIP: None
  selector:
    app: go-app3
  ports:
    - name: http-go-app3
      protocol: TCP
      port: 80
      targetPort: 3000
