apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: go-app3
  name: go-app3-rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-app3
  strategy:
    blueGreen:
      activeService: go-app3-service
      autoPromotionEnabled: false
      previewReplicaCount: 1
      previewService: go-app3-preview-service
  template:
    metadata:
      labels:
        app: go-app3
        version: v0.1.72
    spec:
      containers:
        - image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:v0.1.72
          name: go-app
          env:
            - name: APPNAME
              value: app3
          ports:
            - containerPort: 3000
