apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-example
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
      - image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        name: go-example
        ports:
        - containerPort: 3000
