apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-deployment
spec:
  selector:
    matchLabels:
      app: go-example
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
      - name: go-example
        image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:latest
        ports:
        - containerPort: 3000
