apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-example
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
      - image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:v0.1.61
        name: go-example
        ports:
        - containerPort: 3000
