apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app1
  name: go-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app1
  template:
    metadata:
      labels:
        app: go-app1
    spec:
      containers:
      - env:
        - name: APPNAME
          value: app1
        image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:v0.1.58
        name: go-app
        ports:
        - containerPort: 3000
      - image: envoyproxy/envoy:v1.9.1
        name: envoy
        ports:
        - containerPort: 8786
        resources: {}
        volumeMounts:
        - mountPath: /etc/envoy
          name: config
      volumes:
      - configMap:
          name: envoy-sidecar
        name: config
