name: Get Image and Version from yml file

on:
  workflow_dispatch:
jobs:
  get-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: deployment-config
        
    - name: Get Version from config 
      id: getVersion
      uses: mikefarah/yq@master
      with:
        cmd: yq '.spec.template.metadata.labels.version' 'deployment-config/go-app1/go-app1-blue-deploy.yaml'
        
    - name: Get Image from config 
      id: getImage
      uses: mikefarah/yq@master
      with:
        cmd: yq '.spec.template.spec.containers[0].image' 'deployment-config/go-app1/go-app1-blue-deploy.yaml'

    - name: Echo version and image
      run: |
       echo ${{ steps.getVersion.outputs.result }}
       echo ${{ steps.getImage.outputs.result }}
        
    - name: Update Version and Image to config 
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.template.metadata.labels.version = "${{ steps.getVersion.outputs.result }}" | .spec.template.spec.containers[0].image = "${{ steps.getImage.outputs.result }}"' 'deployment-config/go-app1/go-app1-green-deploy.yaml'

    - name: Commit and push changes
      env:
        GITHUB_EMAIL: satvik@eltropy.com
        GITHUB_NAME: deploy-green
      run: |
       cd deployment-config
       git config user.email ${GITHUB_EMAIL}
       git config user.name ${GITHUB_NAME}
       git commit -m "Make changes to green deployment"
       git push
