apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app2
    deploy: green
  name: go-app2-green-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app2
      deploy: green
  template:
    metadata:
      labels:
        app: go-app2
        version: v0.1.63
        deploy: green
    spec:
      containers:
      - env:
        - name: APPNAME
          value: app2
        image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:v0.1.63
        name: go-app
        ports:
        - containerPort: 3000
