apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: go-app2-destination
spec:
  host: go-app2-service.default.svc.cluster.local
  subsets:
    - name: active
      labels:
        version: v0.1.74
    - name: preview
      labels:
        version: v0.1.78
