apiVersion: v1
kind: Service
metadata:
  name: go-app2-service
spec:
  type: ClusterIP
#  clusterIP: None
  selector:
    app: go-app2
  ports:
  - name: http-go-app2
    protocol: TCP
    port: 80
    targetPort: 3000
