apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app2
    deploy: blue
  name: go-app2-blue-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app2
      deploy: blue
  template:
    metadata:
      labels:
        app: go-app2
        deploy: blue
        version: v0.1.77
    spec:
      containers:
      - env:
        - name: APPNAME
          value: app2
        image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:v0.1.77
        name: go-app
        ports:
        - containerPort: 3000
