apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app2
  name: go-app2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app2
  template:
    metadata:
      labels:
        app: go-app2
    spec:
      containers:
      - env:
        - name: APPNAME
          value: app2
        image: 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:v0.1.63
        name: go-app
        ports:
        - containerPort: 3000
      - image: envoyproxy/envoy:v1.9.1
        name: envoy
        ports:
        - containerPort: 8786
        resources: {}
        volumeMounts:
        - mountPath: /etc/envoy
          name: config
      volumes:
      - configMap:
          name: envoy-sidecar
        name: config
